name: instagram apk

on:
  schedule:
    # 此处是UTC时间，对应北京时间早八点
    - cron: '00 00 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Yakov5776/gh-apkmirror-dl@v1.2
      with:
        org: 'instagram'
        repo: 'instagram'
